import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-single',
  templateUrl: './single.component.html',
  styleUrls: ['./single.component.scss']
})
export class SingleComponent implements OnInit {

  data : any = [
    {id : 0, small : "Develpoment of", big : "Web Apps", url : "web-application", content : "LCMaze blends high-quality material design and effective programming to create dynamic, functional and beautiful sites. If you plan to create a website which perfectly matches your business needs and personal preferences, we can do it. For every project, we put together a dedicated team and make the customer the center of the development process. Whether you have a mere idea of your future web app or a detailed plan, we will apply our technical expertise and help you to make it functional. You will be able to watch the development progress quickly and add your opinions on the go. Your success on the World Wide Web is chiefly determined by the quality of your website. The more sophisticated and authentic your web site appears to a user, the bigger your chance of going a long way in the business. The developers in Intersmart venture outside the customary programming frameworks to create websites with distinct identities on the internet. Our professionals draw on years-long experience to develop attractive online entities that can appeal to the varying senses of users by enhancing the user-friendly engagement. We are a closely-knit team composed of digital marketing experts, PHP developers, Graphic designers, creative directors and content strategists.", img : "webdevelopment.svg"  },
    {id : 1, small : "Develpoment of", big : "C M S", url : "content-management-system", content : "With content being a sort of information exchange, handling it efficiently is a move towards stimulating business enhancement. A regular CMS web development service is a catalog-enriched way with characteristics combined to profit your enterprise. The content team advances to capitalize on performance into a label and it is only achievable with having the best information at the appropriate time and in the correct quantity. For this to happen, it is advised to address CMS website development companies with content management requirements to level the growth principles. This will have a crew of programmers planting their experience to best practice tailored to specifications. Content customization, content quality, creating brand through content and context, granting content ownership, maintaining visual consistancy are the major strategies to be adopted", img : "webdevelopment.svg"  },
    {id : 2, small : "Develpoment of", big : "E-Commerce", url : "e-commerce", content : "If you are looking to update your current website or want to start accepting payments online, we are the right choice for you. Online sales is a major driving force of our economy and is set to grow even more in the coming years. Partner with us and see your business reaching heights. We have the knowledge and experience to provide you with a beautiful online store that not only looks and work great but will eventually prove to be an asset for your company. We help you to bring in new customers and to maintain the current clients. Multiple your product exposure by selling online. What makes us different from other companies is that each website we develop is 100% custom built to our customers' request. We do not use templates or free platforms like other agencies. Every e-commerce website built in our company is unique and made in-house, assuring you get the best of the best. We are an ecommerce development company in Kerala which provides sophisticated e-commerce designs, interactive front-end scripting, and extensive product catalogs. Our developers jointly gather innovative methods and transform ideas into a fine and practical e-commerce store with numerous built-in capabilities. WebCastle media assist you to set up a great e-commerce business that promises to be profitable for your business.", img : "webdevelopment.svg"  },
    {id : 3, small : "Solution for", big : "Backend", url : "backend", content : "MANAGEMENT IS NOW MADE SIMPLE WITH BACKEND DEVELOPMENT SERVICES. Website and mobile applications are the precious assets for any organization. The team of back-end developers supports all those glitters on your site and applications. Only with the efficient backend developer, the customers can have an interactive and good experience on your website. LC MAZE one of the best Backend Development services company offers a great variety of capabilities starting from a simple site to the plenty of IoT devices that are booming in the market. There are myriads of option available with us including PHP, Python, R programming, Java, NodeJS, ExpressJS Development. Backend development is one of the vital components of the application. It helps in the process and manages data for the web and mobile app. We at LC Maze use modern and trendy technology that produces the user-friendly experience combated with better performance. The development industry knows that Nodejs Development Services is a wide community now. They are growing day by day, and IoT is the latest application development using nodeJS. They have a faster quick response and allow you to enable the application interface more quickly. Uber, PayPal, and eBay are some of the popular brands relied upon NodeJs. ",img : "webdevelopment.svg"  },

    {id : 4, small : "Development in", big : "Android", url : "android", content : "Quality is what we are known for. We have constantly ensured our clients of quality and deliverable solutions that suit their necessities. Our team designs and innovates the development of mobile apps that ensure the comfort of use and quality interface. Your android application development company needs a crew of developers that have confirmed expertise in developing android applications and has a comprehensive awareness of your business and customers. Android developers at LC Maze can help you meet every requirement your business would demand. Android apps have a tremendous share in the market. This symbolizes that your app is launched into a competing economic field. App development cost, when contrasted against other platforms, is much more inferior to Android. Consequently, the possibilities for higher ROI are more in case Android app development. As a customer, you can determine the quality of your Android apps. Both high quality and low-quality apps can be produced on the Android platform. Android apps assure easy to sign in employing any social media platforms like Facebook, Google, etc. This ensures a more satisfying user experience. The process of app development in the Android platform is comfortable, as developers can get accustomed to the platform in a brief period.", img : "appdevelopment.svg"  },
    {id : 5, small : "Development in", big : "IOS", url : "ios", content : "Our customized iOS app development services guarantee you a wonderful user experience and high-quality performance. Our talented developers and a strong portfolio of high-quality apps that can meet any customization needs for businesses. Our developers are eager and excited to help grow your business. iPhone apps have a more elevated ROI than Android apps. This is a fact that adds on to the advantages of iOS App development, to a large extent. Invasion into a business’s sensitive enterprise data stayed in apps is a big risk. Based on security, iPhone apps, guard firmware, and software through rigorous security measures. When a user downloads an iPhone app, he can be persuaded of flawless performance and astonishing experience. This trust and goodwill on Apple’s legacy have accomplished to collect a large and loyal consumer base. iPhone apps, custom-built or off-the-shelf, are open to suit all business requirements. iPhone apps are seen to be more productive for businesses due to their certain market reach and better-paying clients. The established user base is the one Apple USP which is additionally one of the best privileges of iOS application development. iPhone users are determined to be tech-savvy and open-minded towards modernization. This presents businesses with various possibilities to craft challenging applications.", img : "appdevelopment.svg"  },
    {id : 6, small : "Develpoment of", big : "Hybrid Apps", url : "hybrid", content : "One of the most effective way of growing your business is to keep it up with the recent trends. And the trend that has evolved in the current times, which continues to keep growing, is the transition of businesses to digital platforms from traditional platforms. Creating a digital representation of your business ideals to make them more accessible can be easily done by getting hybrid apps development services. Hybrid mobile development includes parts of HTML5 and JavaScript which are wrapped inside a native container through which you can get access to the native features of the platforms. Hybrid applications can be said to be the combination of Native applications, which are installed on the device, and HTML5 applications, which are deployed on a server. By opting for the process of hybrid apps development, you can get the right type and application that can cater to your needs with efficiency. We provide Hybrid Application Design, development, testing and maintenance to our clients. A few advantages that you get through us include absolute transparency, high coding standards, experienced developers, latest technology, excellent UX architecture and much more. The team of experienced hybrid mobile apps developers at LC Maze are equipped with the knowledge and expertise required for building such applications. Some of the framework tools that they can work efficiently on include Ionic, React Native, Xamarin, Mag+ and Kinvey. Our Hybrid applications development services also includes high quality Flutter Development Services. Our apps can work across all platforms including iOS, Android and Windows. These applications have advanced functionalities with RTP, SOAP, REST, XML and HTTP integration.", img : "appdevelopment.svg"  },
    {id : 7, small : "Develpoment of", big : "Utility Apps", url : "utility", content : "We completely understand your business category and Create a mobile app, which is according to your business requirements and lets you stand apart from the crowd. Our mobile app developers make amazing apps that can fulfill your dream of having a unique brand recognition and identity. Knowing that mobile app development is a set of services, we accomplish diverse requirements from a Hybrid app to a Native app. We use Design-Led-Engineering Process and with this process we start making prototyping, starting from sketch drawing to app design and wireframe to understand users and their needs to come up with a design that is usable and then starts development to make it a user-centric product by using Flinto or Invision. With this, we have up-front design of the complete product without writing a single line of code. After coming together with product design, the team gets down to bringing everything in design to action. Project managers define details tasks for developers. We know mistakes make this app costly and that is why, we would love to share the thoughts, suggestions and decisions to be discussed with you. While working through the app development stage, we update progress to the clients through project management tool such as Basecamp, and Trello. We are using Mantis and JIRA for bug tracking and to maintain the QA data. We have around 50 different iPhone & Android devices to test application at every mobile applications development process stage. Our Quality analysts test, locate, and fix issues that arise throughout the project. We test all use and problematic edge cases and solve it to ensure app works perfectly without a hindrance. You reach to the last step of app development, where your application needs to be submitted to the for final approval, but it’s not just about submitting your app, it’s the first step of marketing for your app. Our ASO team will suggest you the right way of submitting processes; such as screenshots, video introduction and app title and description for the app.", img : "appdevelopment.svg"  },

    {id : 8, small : "Digital Marketing", big : "Social Media", url : "social-media", content : "Achieve your marketing goals with our out of box strategies and design your success. Social media marketing has become crucial for businesses of all sizes to reach out to their consumers. As one of the foremost Social Media Marketing companies in India, our expertise relies on creating appealing content and providing a cutting-edge Social Media Community Management. We promotes your businesses to establish safe and sound relationships with the target audience and thereby enhance your business growth. We will work with you to determine your online goals and map out a plan that will help you achieve your pre-determined business goals. We provide several traffic building services to enhance your online presence and traffic. Meet with one of our specialists to analyze your results and make data-driven marketing decisions afterward.", img : "digitalmarketing.svg"  },
    {id : 9, small : "Digital Marketing", big : "Web Analytics", url : "web-analytics", content : "Gaining an edge in the online marketplace can be challenging. It’s no longer just about “showing up” by having a website. You need to be executing a digital marketing strategy at a high level to truly succeed. Understanding how your customers are using your website plays a critical role in planning any modern digital marketing campaign. Having a proper analytics implementation will help you gather important insights about your online visitors that you can use to make smart decisions to improve your website’s performance. Our web analytics packages provide an intuitive way to understand the behavior of your website’s visitors, gain insight into your website’s performance and uncover problem areas to maximize your conversions.", img : "digitalmarketing.svg"  },
    {id : 10, small : "Digital Marketing", big : "SEO", url : "seo", content : "How can you get the most visits without spending a lot of money on advertisement? Search Engine Optimization (SEO) does this for you. As one of the reputed SEO companies in India, we suggest our clients the most reliable SEO Services. Our team of SEO Experts put forward their experiences and expertise to improve your website ranking in SERP results and maximize your online presence. Paid search is one of the most efficient means to target and engage with likely customers. A good SEM company can help you accurately manage your campaigns by utilizing your ad budget for the best results. Our specialist team helps businesses turnabout underperforming SEM campaigns besides building completely new campaigns from scratch. Search engine advertising is one of the leading forms of PPC. PPC permits you to bid for ad placement. With the help of PPC, your brand can relinquish a wider range of prospective audiences.", img : "digitalmarketing.svg"  },
    {id : 11, small : "Managemet of", big : "Promotions & Ads", url : "ads", content : "Advertisers are focused on performance metrics like cost-per-acquisition and return on ad spend. With such different goals, it's no wonder that many marketers view organic and paid as separate from one another. Not only can organic and paid marketing work together, but that digital advertising can help you improve your organic efforts. The goal of any ads strategy should be to get a positive return on your investment, which comes down to whether you're getting more revenue out of the ad campaign than the cost you're putting in. How can you determine what your ad spend should be to get the most return on your investment? To start answering that question, we'll need to understand the bidding system used by the ad networks. A bid is the maximum amount of money you're willing to pay for a desired action on your ad. If it sounds like an auction, that's because it is an auction. Ad networks have a limited amount of ad space, and to determine whether or not your ads are shown to your target audience, they run an auction to see how much each advertiser is willing to pay for ad space.", img : "digitalmarketing.svg"  },

    {id : 12, small : "Web Designing", big : "Corporate Websites", url : "corporate-websites", content : "Corporate website development is an important part of today’s business world. Over the past several years, corporate website development and corporate website design have become critical parts to the success of all kinds of companies from small businesses to multinational corporations. Regardless of your product, services, or goals, corporations can only foster growth when they’re expanding their customer base — and the Internet is the best medium to use for growth. That’s why corporate website design is so important in the business world, especially when it’s combined with the right Internet marketing strategy. Suddenly, your company can engage clients from all over the world for a fraction of the cost of traditional advertising media like television or radio. You’re not just a local business — you’re global. As a leading corporate web design company, LC Maze specializes in growing the online presence of companies like yours. Our team includes talented specialists on the cutting edge of corporate website development who are passionate about building business websites from the ground up and tweaking them for optimized results. Best of all, our corporate web development team knows how to keep you ahead of your competition.", img : "webdesigning.svg"  },
    {id : 13, small : "Web Designing", big : "UI/UX Designing", url : "ui-ux-design", content : "LC Maze is focused on friendly attitude and Amazing Design. We are enriched with talented and creative team to fulfill your needs. We are happy to deliver logo design, live video streaming, advertisements,event posters, brochures, websites, invitation cards etc. In today’s visual culture, the combination of text and images are very important, people don’t have much time to read all the matters which is given in the media, so our concentration is to put maximum image representation into your publishing area’s so that the people can recognize you from our design pattern. We always concentrating on the taste of the customer, so that we can creative very special and accurate product what are the customer demands.", img : "webdesigning.svg"  },
    {id : 17, small : "Responsive", big : "Web Designing", url : "responsive-web", content : "With more than 50 percent of the Internet’s traffic coming from mobile users, it’s imperative to provide support for users on-the-go. It’s also best practice for SEO, as Google now follows a mobile-first index, meaning it crawls and views websites from the perspective of a mobile user, not a desktop user. If your website doesn’t support mobile users, Google sees that — and modifies your ranking in search results. That can lead to a lower ranking, pushing your site to page two of search results and away from your target audience. With our responsive design option, we prevent that from happening to your business. For maximum impact, we also offer website copywriting with our web design services. We feature an experienced and specialized team of copywriters. With their expertise in technical and non-technical industries, we can create compelling copy that engages and converts website visitors", img : "webdesigning.svg"  },
    {id : 15, small : "Web Servers", big : "Hosting", url : "hosting", content : "How do you use email? For many email users, paid hosting is wholly unnecessary, but what about when you have important documents like bills, invoices, client contacts or any other pieces of sensitive information stored on your email account? Additionally, can you afford to lose subscribers, customers, etc. by having a clumsy and unprofessional generic email like your.business@gmail.com over your own domain such as info@your.business.com? In addition to the professionalism that having your own domain in your email provides, it’s advised to consider upgrading to email hosting instead of putting your data in the hands of a free email service like Google or Yahoo. Consistently maintaining and supporting email yourself or relying on in-house services will not only add to your expenses, but will also increase the probability of virus infections, as well as hardware and software issues. Such problems could cause email not to function from several hours to days, which is why more businesses are opting for modern email hosting plans. Webmail or a hosting clients vary from provider to provider. Cpanel email is a type of web-hosting email service which lets you send emails and manage more than one email account through a webmail portal or email clients, such as Outlook and Thunderbird via SMTP/POP/IMAP connections and protocols. This service is a good fit for anyone using multiple standard email accounts.", img : "webdesigning.svg"  },
  ];

  private routs: Subscription;
  urlvalue : any;
  smallvalue: any;
  bigvalue: any;
  cntvalue: any;
  imgvalue: any;

  constructor(private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.routs = this.route.params.subscribe(params => {
      this.urlvalue = params['id'];
      this.find();
    });
  }

  find(){
    for(let i = 0; i <= 15; i++){
      if(this.data[i].url === this.urlvalue){
        this.smallvalue = this.data[i].small;
        this.bigvalue = this.data[i].big;
        this.cntvalue = this.data[i].content;
        this.imgvalue = this.data[i].img;
      }
    }
  }
}
