import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-single',
  templateUrl: './single.component.html',
  styleUrls: ['./single.component.scss']
})
export class SingleComponent implements OnInit {

  data : any = [
    {id : 0, small : "Develpoment of", big : "Web Apps", url : "web-application", content : "LCMaze creates stunning web applications keeping in mind the emerging trends of the internet. Your prosperity on the World Wide Web is mostly controlled by the value of your site. We strive to achieve that delicate balance between excellent branding, brilliant user experience, and speedy performance in our web applications. Our web development team has significant experience in deploying custom-built web applications that get the desired results. We combine top-notch material design and effective programming to make dynamic, useful, and excellent web applications. For each project, we set up a committed group and make the client the focal point of the development cycle. The more modern and user friendly your site appears to a client, the greater your possibility of going far in the business. Whether you are looking for a simple web application for your brand or a custom-built E-commerce website for your online store, LCMaze has got it covered.", img : "webdevelopment.svg"  },
    {id : 1, small : "Develpoment of", big : "C M S", url : "content-management-system", content : "A content management system is a system designed to manage content online. Content is important and taking care of it productively is a move towards invigorating business improvement. Content customization, content quality, making brand through substance and setting, giving substance proprietorship, keeping up visual consistency are the significant systems to be received. We specialize in content management systems that are custom-built as well as integration such as WordPress, Joomla, Drupal, or hosted solutions like Shopify. ", img : "webdevelopment.svg"  },
    {id : 2, small : "Develpoment of", big : "E-Commerce", url : "e-commerce", content : "Online commerce is here to stay and is set to become considerably more in the coming years. We can help you grow your business with our unified eCommerce websites. We have the information and experience to furnish you with a delightful online store that looks and works extraordinary as well as will in the long run end up being a resource for your organization. We will help you to acquire new clients and to keep up the current customers. What makes us not quite the same as other organizations is that every site we create is 100% exceptionally worked to our clients'satisfaction. We don't utilize layouts to create websites for your business. Each web-based business site made by us is one of a kind and made in-house, guaranteeing you outwit the best. Our engineers together accumulate creative techniques and change thoughts into a fine and viable web-based business store with various implicit abilities. We specialize in beautiful themes that are responsive and custom-built. Check out our portfolio for more details.", img : "webdevelopment.svg"  },
    {id : 3, small : "Solution for", big : "Backend", url : "backend", content : "We have the experience to build backend solutions of discretionary, multifaceted nature, and performance. Website and versatile applications based on it are valuable resources for any company. Our group of back-end designers underpins each one of those details on your site and applications. With our solutions, the users can have an intuitive and great experience on your site. There are lots of choices accessible to us including PHP, Python, R programming, Java, NodeJS, ExpressJS Development. Backend improvement is one of the imperative segments of the application. It helps to oversee information for the web and portable applications. Nodejs Development Services is a wide network now. It is developing step by step, and IoT is the most recent application improvement utilizing nodeJS. Uber, PayPal, and eBay are a portion of the mainstream brands depended upon NodeJs. We harness this technological advantage of Node JS to create amazing web experiences for your users as backend solutions.",img : "webdevelopment.svg"  },

    {id : 4, small : "Development in", big : "Android", url : "android", content : "Google’s Android OS is the most popular mobile device operating system on the planet. Thus, having an android app for your business is sometimes necessary for giving your customers the exact experience of your brand. Quality is the thing that we are known for when it comes to Android app development. We have continually guaranteed our customers value and deliverable arrangements that suit their necessities. Your business needs a team of designers who have affirmed the ability in creating android applications and have a thorough familiarity with your business and clients. Android developers at LCMaze can assist you with meeting each necessity your business would request. As a client, you can decide the nature of your Android applications. Android applications guarantee simple to sign in utilizing any online media tools like Facebook, Google, and so on.", img : "appdevelopment.svg"  },
    {id : 5, small : "Development in", big : "IOS", url : "ios", content : "With high standards, iOS is one of the best mobile phone operating systems out there. We have developed numerous applications for iPhones for a wide variety of businesses. LCMaze has a zeal for iPhone app development and this makes us one of the best in the market. Our engineers are experts in their trade and will cater to your needs from the initial stages to the delivery of the product as well as in maintenance afterward. Our iOS application development team promises you a magnificent client experience and top-notch execution. Our engineers are energetic and eager to help develop your business. iPhone applications have a more raised ROI than Android applications. In light of security, iPhone applications, monitor firmware, and programming through thorough safety efforts. At the point when a client downloads an iPhone application, they can be convinced of an impeccable execution and a bewildering experience. This trust and generosity on Apple's heritage have achieved to gather an enormous and faithful shopper base. iPhone applications are available to suit all business prerequisites. iPhone applications are believed to be more gainful for organizations because of their specific market reach and better-paying customers. iPhone clients are resolved to be educated and receptive towards modernization. This presents organizations with different prospects in testing applications. We can help you grow by developing an iOS app for your business.", img : "appdevelopment.svg"  },
    {id : 6, small : "Develpoment of", big : "Hybrid Apps", url : "hybrid", content : "Hybrid apps are the trend of the day. They contain the best of both worlds - features of native apps and elements from web applications. There are many advantages to using a hybrid app for your business. Controlled costs, independence from app stores, reusing the code are just some of them. We give hybrid application design, development, testing, and support to our customers. The group of experienced hybrid portable application designers at LCMaze are furnished with the information and skill needed for building such applications. The platforms that they can work proficiently are Ionic, React Native, Xamarin, Mag+, and Kinvey. Our applications can work on iOS, Android, and Windows. These applications have progressed functionalities with RTP, SOAP, REST, XML, and HTTP coordination.", img : "appdevelopment.svg"  },
    {id : 7, small : "Develpoment of", big : "Utility Apps", url : "utility", content : "These are apps that add functionalities to the device. This will also help your systems run better. With our experience in building versatile applications, we are able to provide you with utility applications as well. We totally comprehend your business requirements and create a portable application, which is as per your business necessities and lets you stand different from the group. Our engineers make stunning applications that can satisfy your requirements about having a remarkable brand acknowledgment. We use a design-led-engineering process. With this, we have a direct front plan of the total item without composing a single line of code. While working through the application advancement stage, we update progress to the customers through task board applications, for example, Basecamp, Trello, etc. We have around fifty distinctive iPhone and Android gadgets to test applications at each advancement measure stage. Our quality experts test, find and fix errors that emerge all through the development. We test all utilization and tricky edge cases and comprehend it to guarantee application works consummately without a deterrent. Our team members will recommend to you the correct method of submitting measures, for example, screen captures, video presentation, and application title and depiction for the application.", img : "appdevelopment.svg"  },

    {id : 8, small : "Digital Marketing", big : "Social Media", url : "social-media", content : "Social media helps businesses to share their ideas, information through communities. It also helps brands to communicate with their followers. You can accomplish your marketing objectives with our methodologies and plan your prosperity. Web-based media advertising is essential for organizations to contact their customers. As one of the experienced social media marketing company, our skill depends on making engaging content and giving the best Social Media Community Management. We will work with you to decide your online objectives and guide out an arrangement that will assist you with accomplishing your pre-decided business objectives. We will help you to improve your online presence and traffic.", img : "digitalmarketing.svg"  },
    {id : 9, small : "Digital Marketing", big : "Web Analytics", url : "web-analytics", content : "Web analytics can be used as a tool for business and market research and to improve the effectiveness of a website. We can use it to understand and optimize web usage. Lcmaze helps businesses to execute an advanced advertising procedure at an elevated level to really succeed. Seeing how clients are utilizing your website assumes a basic function in arranging any advanced computerized showcasing effort. Having an appropriate examination of usage will assist you with significant experiences about your online visitors that you can use to settle on keen choices to improve your site's presentation. Our web analytics tools give a natural method to comprehend the conduct of your site's visitors, gain understanding into your site's performance, and reveal problem areas to augment your lead conversions.", img : "digitalmarketing.svg"  },
    {id : 10, small : "Digital Marketing", big : "SEO", url : "seo", content : "SEO refers to the technique of improving the website to increase its visibility for relevant searches. We can increase the quality as well as quantity of the visits to the website by implementing different SEO techniques. Lcmaze can help you to get the most site visits without spending a ton of cash on commercials. SEO does this for you. We recommend our customers with the best SEO Services. Our SEO Experts set forward their best ideas to improve your site positioning in SERP results and boost your online presence. A paid search is one of the most productive intends to target and draw in with likely clients. A decent SEM organization can help you precisely deal with your missions by using your advertisement spending plan for the best outcomes. Search engine advertising is one of the main types of PPC. PPC grants you to offer for advertisement placement. With the assistance of PPC, your brand can enjoy a more extensive scope of forthcoming audience.", img : "digitalmarketing.svg"  },
    {id : 11, small : "Managemet of", big : "Promotions & Ads", url : "ads", content : "Promotions and advertisements are used to communicate the product, brand, or service to the user. The main idea behind promotions is to make people aware, attract, and induce to buy the product. It is no big surprise that numerous advertisers see organic and paid as independent from each other. The objective of any advertisements system ought to be to get a positive profit for your speculation, which comes down to whether you're getting more income out of the promotion crusade than the cost you're paying. We'll have to comprehend the offering framework utilized by the advertisement organizations. Promotion networks have a restricted measure of advertisement space, and to decide if your advertisements appear to your intended interest group, they run a closeout to perceive how much every promoter is happy to pay for advertisement space. At LCMaze, we take care of every aspect of advertising from design to development to cater to your various promotional needs.", img : "digitalmarketing.svg"  },

    {id : 12, small : "Web Designing", big : "Corporate Websites", url : "corporate-websites", content : "Every company needs to have a professional presence online with a state of the art website that looks elegant to the user. This image should also be an accurate representation of what the company stands for. At LCMaze, we take care of the branding of our client’s businesses and we know how important a corporate website is. Corporate website development is a significant part of the present business world. In the course of recent years, corporate website development and design have become basic parts of the accomplishment of a wide range of organizations from independent ventures to global companies. That is the reason corporate web design is so significant in the business world, particularly when it's joined with the correct internet advertising methodology. Your organization can connect with customers from everywhere over the world for a small amount of the expense of traditional publicizing media like TV or radio. You're not simply a nearby business — you're worldwide. LC Maze has practical experience in developing the online presence of organizations like yours. The best part is that our corporate web development team realizes how to keep you in front of your opposition.", img : "webdesigning.svg"  },
    {id : 13, small : "Web Designing", big : "UI/UX Designing", url : "ui-ux-design", content : "We understand that looks and style are important when it comes to an online presence for your brand. At LCMaze, we aim to create designs that are easy to use and is a feast to the eyes. We are centered around our cordial disposition and amazing design. Our company is enhanced by a skilled and imaginative group of designers to satisfy your requirements. We are glad to develop logos, live video streaming, advertisements, event banners, pamphlets, websites, greeting cards, and so forth. In the present visual culture, the mix of text and pictures are significant. We continually focus on the taste of the client, so we can create exceptional and exact items the client requires.", img : "webdesigning.svg"  },
    {id : 17, small : "Responsive", big : "Web Designing", url : "responsive-web", content : "A responsive web design is a design that is compatible with all devices. In today’s world, where 5.2 billion people use a mobile phone, businesses should have websites that look good on all devices. With an excess of 50% of the Internet's traffic coming from portable clients, it's a necessity to offer help to users on the go. It's additionally a best practice for SEO, as Google currently follows a mobile-first index, which means it crawls and views websites from the viewpoint of a mobile client, and not a desktop user. In the event that your website doesn't uphold mobile clients, Google sees that — and alters your positioning in index items. That can prompt a lower positioning, pushing your site to page two of indexed lists and away from your intended interest group. With our responsive design choice, we keep that from happening to your business. For the greatest effect, we additionally offer website copywriting with our website design services. We highlight an accomplished and specialized group of content marketing specialists. With their mastery of technological and non-technological ventures, we can make convincing content that draws in website visitors.", img : "webdesigning.svg"  },
    {id : 15, small : "Web Servers", big : "Hosting", url : "hosting", content : "Web hosting simply means a service that allows a user or a business to post content on their website. For some email clients, paid hosting is completely unnecessary. However, something should be done about when you have significant reports like bills, solicitations, customer contacts, or some other bits of delicate data put away on your email account. Also, businesses will not be able to lose endorsers, clients, and so on by having an awkward and amateurish conventional email like your.business@gmail.com over your own mail id, for example, info@your.business.com. Having your own domain in your email gives the associated professionalism to your business. It is also encouraged to consider moving up to email hosting as opposed to placing your information in the possession of a free email service like Google or Yahoo. Keeping up and supporting emails yourself or depending on in-house administrations won't just add to your costs, but will also build the likelihood of virus attacks, just as hardware and software issues. Such issues could cause email not to work from a few hours to days, which is the reason more organizations are picking email hosting plans. Cpanel email is a kind of web-facilitating email service that lets you send messages and oversee more than one email account through a webmail portal or email customers. We can also hold numerous email accounts with one such hosting. Thus, there are many positives in choosing webmail hosting instead of standard email providers.", img : "webdesigning.svg"  },
  ];

  private routs: Subscription;
  urlvalue : any;
  smallvalue: any;
  bigvalue: any;
  cntvalue: any;
  imgvalue: any;

  constructor(private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.routs = this.route.params.subscribe(params => {
      this.urlvalue = params['id'];
      this.find();
    });
  }

  find(){
    for(let i = 0; i <= 15; i++){
      if(this.data[i].url === this.urlvalue){
        this.smallvalue = this.data[i].small;
        this.bigvalue = this.data[i].big;
        this.cntvalue = this.data[i].content;
        this.imgvalue = this.data[i].img;
      }
    }
  }
}
